### ISSUE TITLE
Make NVika available from chocolatey

### ISSUE THREAD

**Issue by roh85** [laedit/vika#13]
I would like to use NVika in AppVeyor. It would be nice if I could just choco install NVika and use it from commandline. I would like to suggest to make a package and upload it to chocolatey gallery.

**Comment by laedit** [comment]
I didn't know I have some users on this project :smile: 
It was already planned but I'll try to do it ASAP.

**Comment by roh85** [comment]
https://gripdev.wordpress.com/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/

https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart

**Comment by laedit** [comment]
Thanks but I already have a couple of packages in Chocolatey so I know how to do it, I just don't have the time to do it right now.

**Comment by laedit** [comment]
Submitted to chocolatey, currently under review before approval.
https://chocolatey.org/packages/nvika

**Comment by laedit** [comment]
The package is now publicly available.

**Comment by roh85** [comment]
Thank you very much!
