### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json' when running NVika in AppVeyor

### ISSUE THREAD

**Issue by roh85** [laedit/vika#15]
I get an error when using NVika in AppVeyor. I installed Nvika using chocolatey.

See the exception below:

The following build servers has been detected:
	- AppVeyor
Report path is 'inspectcodereport.xml'
Report type is 'InspectCode'
40 issues was found
An unexpected error occurred:
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not mat
ch the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at NVika.BuildServers.AppVeyor.WriteMessage(Issue issue)
   at NVika.ParseReportCommand.Execute(String[] reportPaths)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at NVika.Program.Run(String[] args)
 
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging,

AppVeyor log:
https://ci.appveyor.com/project/roh85/gitcitestrepo

My AppVeyor.yml

version: 1.0.{build}
os: Windows Server 2012 R2
configuration:
- Release
- Debug
init:
- ps: 'Get-ChildItem Env:'
environment:
  COVERALLS_REPO_TOKEN:
    secure: o8b2zjTYPnMUPBdCzXAvZZnAEkRvLdGE7MNTDOC5R/JURTxu/JcAprXPyOkOPtdx
install:
- ps: >-
    choco install resharper-clt -y

    choco install opencover -source https://nuget.org/api/v2/

    choco install coveralls.io -source https://nuget.org/api/v2/

    choco install nvika -y
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: GitCITestRepo.sln
  publish_nuget: true
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    inspectcode /o="inspectcodereport.xml" "GitCITestRepo.sln"

    NVika "inspectcodereport.xml" --debug --includesource

**Comment by roh85** [comment]
I do not get this exception when running nvika local on my dev machine

**Comment by laedit** [comment]
My bad, I forgot to include the config file in the release.
I will submit a new version asap.

**Comment by laedit** [comment]
The v0.1.1 has been submitted to chocolatey: https://chocolatey.org/packages/nvika/0.1.1

**Comment by roh85** [comment]
The package is now working as expected. Thanks!
