### ISSUE TITLE
Add InspectCode full message to AppVeyor details

### ISSUE THREAD

**Issue by roh85** [laedit/vika#17]
The inspectcode messages are truncated in the message view in AppVeyor.

![image](https://cloud.githubusercontent.com/assets/3336504/12881962/4d88ce84-ce4e-11e5-9654-4046724cfb7f.png)

Please add the full message details to AppVeyor. The build-worker-api supports the details element.

https://www.appveyor.com/docs/build-worker-api

This makes reviewing the compilation messages easier.

**Comment by laedit** [comment]
The message is visible in his entirety with the tooltip, is this not enough?
I don't see the added value to repeat the same informations.

**Comment by laedit** [comment]
It seems that the detail isn't displayed: https://ci.appveyor.com/project/laedit/vika/build/0.1.2-PullRequest.18+3%20%28Build%2062%29/messages

**Comment by roh85** [comment]
You are correct about the tooltip, did not notice it. 
It has some minor drawbacks. For example when I want to be able to copy the message to a colleague to pick up the message and fix it. But then again it is possible to copy it from the AppVeyor build log.

**Comment by roh85** [comment]
For now close the PR and the issue. We will use AppVeyor and Vika as-is for some time and see how it fits our daily dev work. If still a problem in the future I can re-open the PR.

**Comment by laedit** [comment]
Good for me.
A solution could also be an evolution in AppVeyor: add the possibility to expand the message.

**Comment by laedit** [comment]
In fact there already have an [issue](https://github.com/appveyor/ci/issues/23).

**Comment by laedit** [comment]
Well I can see now that I was wrong, and since I don't think that AppVeyor will fix their issue soon, I will add this in the next release.

**Comment by laedit** [comment]
Well, they are still not displayed in AppVeyor :cry:, so I opened a [ticket](http://help.appveyor.com/discussions/questions/2620-build-message-detail-not-displayed).

**Comment by laedit** [comment]
And it has been fixed! 🎉

**Comment by roh85** [comment]
awesome, thanks!
